### ISSUE TITLE
Progress bar showing full at 80%

### ISSUE THREAD

**Issue by githubaamod** [calebkiage/flutter_animated_circle_progress#1] opened 2020-01-29 07:24 UTC
hello ,

i have used this code in project but at 80% its showing full circle completed. 
its not showing 20% remaining in lighter color. 

Thanks in advance.

**Comment by calebkiage** [comment] 2020-02-03 21:50
Hello, I'll try to reproduce this and get back to you. To make the process faster for me, could you tell me what platform the issue happens in?

**Comment by calebkiage** [comment] 2020-02-04 23:16
Hey @githubaamod, I've tested using an emulator on Flutter 1.12 and everything seems to be working fine. I will close this issue hoping it went away. However, if you can provide reproduction steps, feel free to contact me. To make sure the issue is not in your code, try to use this in an empty sample project.

**Closed as completed by calebkiage** 2020-02-04 23:16 UTC

**Comment by githubaamod** [comment] 2020-02-05 05:32
Hi ,

thanks for reply. I have used you code in different way and passing value to circular progress indicator manually.  below is how i have changed your code.

**circle_progress.dart**

```
import 'package:cmpic/widgets/circle_progress_bar.dart';
import 'package:cmpic/widgets/textboxes.dart';
import 'package:flutter/material.dart';

double progressPercent = 0;
int progressPercentINT = 0;

class ProgressCard extends StatefulWidget {
  final int totalslots;
  final int filledSlots;

  ProgressCard({@required this.totalslots, @required this.filledSlots});

  @override
  _ProgressCardState createState() => _ProgressCardState();
}

class _ProgressCardState extends State<ProgressCard> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    progressPercent = (widget.filledSlots / widget.totalslots) * 100;
    progressPercentINT = progressPercent.toInt();
    print("progressPercent = " + progressPercentINT.toString());
  }

  @override
  Widget build(BuildContext context) {
    Color foreground = Colors.green;

    if (progressPercent >= 0.8) {
      foreground = Colors.red;
    } else if (progressPercent >= 0.5) {
      foreground = Colors.orange;
    }

    Color background = foreground.withOpacity(0.2);
    return Container(
      width: 75,
      height: 75,
      // color: Colors.blue,
      child: Stack(
        children: <Widget>[
          Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(progressPercentINT.toString() + " %"),
                Text("slots filled")
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(0.0),
            child: GestureDetector(
              behavior: HitTestBehavior.translucent,
              child: CircleProgressBar(
                backgroundColor: background,
                foregroundColor: foreground,
                value: progressPercent,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**circle_progress_bar.dart**


```
import 'dart:math' as Math;

import 'package:flutter/widgets.dart';

class CircleProgressBar extends StatelessWidget {
  final Color backgroundColor;
  final Color foregroundColor;
  final double value;

  const CircleProgressBar({
    Key key,
    this.backgroundColor,
    @required this.foregroundColor,
    @required this.value,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final backgroundColor = this.backgroundColor;
    final foregroundColor = this.foregroundColor;
    return AspectRatio(
      aspectRatio: 1,
      child: CustomPaint(
        child: Container(),
        foregroundPainter: CircleProgressBarPainter(
          backgroundColor: backgroundColor,
          foregroundColor: foregroundColor,
          percentage: this.value,
        ),
      ),
    );
  }
}

// Draws the progress bar.
class CircleProgressBarPainter extends CustomPainter {
  final double percentage;
  final double strokeWidth;
  final Color backgroundColor;
  final Color foregroundColor;

  CircleProgressBarPainter({
    this.backgroundColor,
    @required this.foregroundColor,
    @required this.percentage,
    double strokeWidth,
  }) : this.strokeWidth = strokeWidth ?? 3;

  @override
  void paint(Canvas canvas, Size size) {
    final Offset center = size.center(Offset.zero);
    final Size constrainedSize =
        size - Offset(this.strokeWidth, this.strokeWidth);
    final shortestSide =
        Math.min(constrainedSize.width, constrainedSize.height);
    final foregroundPaint = Paint()
      ..color = this.foregroundColor
      ..strokeWidth = this.strokeWidth
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.stroke;
    final radius = (shortestSide / 2);

    print("shortestSide = " + shortestSide.toString());
    print("radius = " + radius.toString());

    // Start at the top. 0 radians represents the right edge
    final double startAngle = -(2 * Math.pi * 0.25);
    final double sweepAngle = (2 * Math.pi * (this.percentage ?? 0));

    print("startAngle = " + startAngle.toString());
    print("sweepAngle = " + sweepAngle.toString());
    print("this.percentage = " + this.percentage.toString());
    print("PaintingStyle.stroke = " + PaintingStyle.stroke.toString());

    // Don't draw the background if we don't have a background color
    if (this.backgroundColor != null) {
      final backgroundPaint = Paint()
        ..color = this.backgroundColor
        ..strokeWidth = this.strokeWidth
        ..style = PaintingStyle.stroke;
      canvas.drawCircle(center, radius, backgroundPaint);
    }

    print("center = " + center.toString());

    canvas.drawArc(
      Rect.fromCircle(center: center, radius: radius),
      startAngle,
      sweepAngle,
      false,
      foregroundPaint,
    );
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    final oldPainter = (oldDelegate as CircleProgressBarPainter);
    return oldPainter.percentage != this.percentage ||
        oldPainter.backgroundColor != this.backgroundColor ||
        oldPainter.foregroundColor != this.foregroundColor ||
        oldPainter.strokeWidth != this.strokeWidth;
  }
}
```

**Comment by githubaamod** [comment] 2020-02-05 05:34
using this code i am calculating and showing progress indicator as per inputs .Below is how i have displayed it on screen

```
                    Positioned(
                      top: 40,
                      left: 140,
                      child: ProgressCard(
                          totalslots: 25000, filledSlots: 20000),
                    ),
```

 Let me know if any else if required from my side. 

Thanks in advance.

**Comment by calebkiage** [comment] 2020-02-05 19:01
@githubaamod, your issue is that the `CircleProgressBar.value` needs a double value between 0 and 1. See the code at [circle_progress_bar.dart#L166](https://github.com/calebkiage/flutter_animated_circle_progress/blob/master/lib/circle_progress_bar.dart#L166) that does the math. The angles provided to our `canvas.drawArc` function are represented in [radians](https://en.wikipedia.org/wiki/Radian) where a full circle (360 degrees) is 2π (~6.3) radians. When you use 80 as the value, the function gives the sweep angle as 502.6 radians. The reason it appears full is because the sweep angle is greater than the angle of a full circle. I hope this helps

**Comment by githubaamod** [comment] 2020-02-06 07:19
Hello ,

Ohh now i got where was the problem.. Issue solved ..

Thank you very very much .. :)

**Comment by calebkiage** [comment] 2020-02-06 18:21
You're welcome. Good luck with your app.
